export {default as Home} from './Home/Home'
export {default as NotFound} from './NotFound'
export {default as Login} from './Login/Login'
export {default as Register} from './Register/Register'
export {default as Products} from './Products/Products'
export {default as Cart} from './Cart/Cart'